### ISSUE TITLE
Failure in ruby-rnp test on `rnp_key_get_primary_uid failed`

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1539]
## Description

https://github.com/rnpgp/rnp/runs/2923253185?check_suite_focus=true

```sh
2021-06-27T01:33:03.7523470Z Failures:
2021-06-27T01:33:03.7523680Z 
2021-06-27T01:33:03.7524190Z   1) Rnp::Key 4BE147BB22DF1E60 raises an error when requesting primary userid
2021-06-27T01:33:03.7524810Z      Failure/Error: raise klass.new(msg, rc)
2021-06-27T01:33:03.7525110Z 
2021-06-27T01:33:03.7525400Z      Rnp::Error:
2021-06-27T01:33:03.7526300Z        rnp_key_get_primary_uid failed - (rc: 0x10000002): Bad parameters
2021-06-27T01:33:03.7527220Z      # ./lib/rnp/error.rb:35:in `raise_error'
2021-06-27T01:33:03.7528020Z      # ./lib/rnp/utils.rb:21:in `call_ffi'
2021-06-27T01:33:03.7528850Z      # ./lib/rnp/key.rb:440:in `string_property'
2021-06-27T01:33:03.7529700Z      # ./lib/rnp/key.rb:74:in `primary_userid'
2021-06-27T01:33:03.7530750Z      # ./spec/key/properties/4BE147BB22DF1E60_spec.rb:51:in `block (3 levels) in <top (required)>'
2021-06-27T01:33:03.7531220Z 
2021-06-27T01:33:03.7531630Z Finished in 42.27 seconds (files took 1.02 seconds to load)
2021-06-27T01:33:03.7532100Z 247 examples, 1 failure
2021-06-27T01:33:03.7532360Z 
2021-06-27T01:33:03.7532670Z Failed examples:
2021-06-27T01:33:03.7532920Z 
2021-06-27T01:33:03.7533600Z rspec ./spec/key/properties/4BE147BB22DF1E60_spec.rb:49 # Rnp::Key 4BE147BB22DF1E60 raises an error when requesting primary userid
2021-06-27T01:33:03.7534190Z 
```

## Steps to Reproduce

As above.

## Expected Behavior

Passing.

## Actual Behavior

Failure.

**Comment by ni4** [comment]
Fixed via https://github.com/rnpgp/ruby-rnp/pull/72
