### ISSUE TITLE
cli_tests-Encryption failure on Windows

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/rnp#2139]
After botan upgrade to 3.1 cli_tests-Encryption fails on Windows
It happens in 30% of cases but always with the following test and settings:  --aead --cipher AES192 

```
2023-10-28T19:09:54.7436902Z ======================================================================
2023-10-28T19:09:54.7437398Z ERROR: test_sym_encryption__rnp_aead (__main__.Encryption.test_sym_encryption__rnp_aead)
2023-10-28T19:09:54.7437619Z ----------------------------------------------------------------------
2023-10-28T19:09:54.7437779Z Traceback (most recent call last):
2023-10-28T19:09:54.7438272Z   File "D:\a\rnp\rnp\src\tests\cli_tests.py", line 4166, in test_sym_encryption__rnp_aead
2023-10-28T19:09:54.7438609Z     rnp_sym_encryption_rnp_aead(size, cipher, z, [aead, bits], GPG_AEAD)
2023-10-28T19:09:54.7439081Z   File "D:\a\rnp\rnp\src\tests\cli_tests.py", line 731, in rnp_sym_encryption_rnp_aead
2023-10-28T19:09:54.7439257Z     rnp_decrypt_file(enc, dst)
2023-10-28T19:09:54.7439653Z   File "D:\a\rnp\rnp\src\tests\cli_tests.py", line 402, in rnp_decrypt_file
2023-10-28T19:09:54.7439872Z     raise_err('rnp decryption failed', out + err)
2023-10-28T19:09:54.7440370Z   File "D:\a\rnp\rnp\src\tests\cli_common.py", line 39, in raise_err
2023-10-28T19:09:54.7440536Z     raise CLIError(msg, log)
2023-10-28T19:09:54.7440734Z cli_common.CLIError: rnp decryption failed
```

```
2023-10-28T19:09:54.7079341Z D:/a/rnp/rnp/build/src/rnp/rnp.exe rnp.exe --homedir C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\.rnp --bzip2 --aead --cipher AES192 --pass-fd 4 --passwords 1 -c C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.txt --output C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.enc
2023-10-28T19:09:54.7079545Z Working directory: D:\a\rnp\rnp\build\src\tests
2023-10-28T19:09:54.7079551Z 
2023-10-28T19:09:54.7079557Z 
2023-10-28T19:09:54.7081399Z D:/a/rnp/rnp/build/src/rnp/rnp.exe rnp.exe --homedir C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\.rnp --pass-fd 4 --decrypt C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.enc --output C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.rnp
2023-10-28T19:09:54.7081605Z Working directory: D:\a\rnp\rnp\build\src\tests
2023-10-28T19:09:54.7081616Z 
2023-10-28T19:09:54.7081621Z 
2023-10-28T19:09:54.7081764Z rnp decryption failed
2023-10-28T19:09:54.7081771Z 
2023-10-28T19:09:54.7081867Z ERROR
```

**Comment by ni4** [comment]
@maxirmx Did this happen during the upgrade from 3.0 to 3.1, or from 2.x?

**Comment by maxirmx** [comment]
> @maxirmx Did this happen during the upgrade from 3.0 to 3.1, or from 2.x?

Unfortunately the transition was from 2.x to 3.1 so I do not know

**Comment by maxirmx** [comment]
@ni4
It looks like in the faulty case  ```run_proc_windows``` returns ```0xC0000005  (Access violation)``

**Comment by ni4** [comment]
Issue is on Botan's side: https://github.com/randombit/botan/issues/3812
